name: "coreplatform-batch-management"
description: "Starts, stops, and validates Core Platform Batch runners and schedulers"

inputs:
  artificial-duration:
    required: false
    description: "The duration to artificially delay the action"

runs:
  using: "composite"
  steps:

    - name: Run action code
      env:
        DURATION: ${{ inputs.artificial-duration }}
      shell: bash
      run: |
        cd ${{ github.action_path }}
        aws s3 cp s3://giftbit-deployment-artifacts/test-action-go-binary .
        chmod +x test-action-go-binary
        ./test-action-go-binary
      